language: node_js

node_js:
  - "lts/*"

script:
  - npm run build

deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    branch: master
    tags: true
